[workspace]
resolver = "2"
members = [
    "core-lib",
    # "cli",  # Not needed for Cloud Run deployment
    # "grpc-api",  # Not needed if using REST API
    "rest-api"
]

[workspace.dependencies]
core-lib = { path = "core-lib" }