edition = "2021"
max_width = 100
use_small_heuristics = "Max"
reorder_imports = true
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Module"

