[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[dependencies]
secrecy = "0.10.3"
thiserror = "2.0.12"
libc = "0.2.171"
zeroize = { version = "1.8.1", features = ["derive"] }
rand = "0.9.1"
once_cell = "1.18.0"
num_cpus = "1.16"
p256 = { version = "0.13", features = ["ecdsa", "sha256"] }
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }

# Platform-specific dependencies
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Security_Cryptography",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"
security-framework = "2.9"

[target.'cfg(target_os = "linux")'.dependencies]
# Linux uses standard libc, no additional dependencies needed

[build-dependencies]
cc = "1.2.18"
bindgen = "0.71.1"

[dev-dependencies]
core-lib = { path = "." }

[features]
default = []
derand = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(rust_analyzer)"] }