[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[dependencies]
zeroize = { version = "1.6", features = ["derive"] }
secrecy = "0.8"
rand_core = "0.6"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"

[dev-dependencies]
core-lib = { path = "." }

[features]
default = []
derand = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(rust_analyzer)"] }