[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[dependencies]
secrecy = "0.10.3"
thiserror = "2.0.12"
libc = "0.2.171"
zeroize = "1.8.1"
rand = "0.9.1"

[build-dependencies]
cc = "1.2.18"
bindgen = "0.71.1"

[dev-dependencies]
core-lib = { path = "." }

[features]
default = []
derand = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(rust_analyzer)"] }