name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  SKIP_VENDOR_INTEGRITY: 1

jobs:
  test:
    name: Test Before Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Run tests
      run: cargo test --all-features
      working-directory: core-lib
    
    - name: Run security tests
      run: |
        cargo test --test kat_tests --all-features
        cargo test --test memory_safety_tests --all-features
      working-directory: core-lib

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Login to crates.io
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
    
    - name: Publish crate
      run: cargo publish
      working-directory: core-lib
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          
          See CHANGELOG.md for detailed changes.
          
          ## Installation
          
          Add to your Cargo.toml:
          ```toml
          [dependencies]
          cypheron-core = "${{ github.ref_name }}"
          ```
        draft: false
        prerelease: false