name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install C dependencies
        run: sudo apt-get update && sudo apt-get install -y clang make build-essential

      - name: Build Kyber C reference implementation
        working-directory: ./kyber/ref
        run: |
          make clean
          make
          cp libkyber_ref.a ../../Projects/pq-core/core-lib/native/ref/

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build and Test Rust project
        working-directory: ./Projects/pq-core
        run: cargo test --package core-lib
